{% set name = "pychrono" %}
{% set version = "4.0.0" %}
{% set build = 3 %}
{% set sha256 = "1c218e7b8de3674277826dc8f751413746f1b2d94698f029ce41a0caaacdc0c1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/projectchrono/chrono/tarball/develop
  fn: develop.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - swig 4.0.1
  host:
    - python 3
    - eigen
  run:
    - python 3

test:
  commands:
     python -c "import os, site; os.environ['PYTHONPATH'] = site.getsitepackages()[0]; import pychrono"

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A physics engine for constrained multi-flexible-body dynamics

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
