{% set name = "pychrono" %}
{% set version = "4.0.0" %}
{% set build = 3 %}
{% set sha256 = "7324e9ce248c798d40c2db94f5712fff1fe13c78c12b5198583761ed62a48296" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davidbrochart/chrono/tarball/fix_termios
  fn: develop.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - swig 4.0.1
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  host:
    - python
    - eigen
    - llvm-openmp  # [osx]
  run:
    - python
    - llvm-openmp  # [osx]

test:
  imports:
     - pychrono

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A physics engine for constrained multi-flexible-body dynamics

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
