{% set name = "pychrono" %}
{% set version = "4.0.0" %}
{% set build = 3 %}
{% set sha256 = "7ee0d972cf46bb5ea2342b6b38c77cce4dc502562515983ed7551152db7c219d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/projectchrono/chrono/tarball/develop
  fn: develop.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - swig 4.0.1
  host:
    - python 3
    - eigen
    - openmp
  run:
    - python 3
    - openmp

test:
  imports:
     - pychrono

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A physics engine for constrained multi-flexible-body dynamics

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
