{% set name = "pychrono" %}
{% set version = "4.0.0" %}
{% set build = 3 %}
{% set sha256 = "ec86fe31ac927a65bf765226c3dc13c170580d0cb797f984d82725b54ddefb04" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/projectchrono/chrono/tarball/develop
  fn: develop.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - swig 4.0.1
  host:
    - python 3
    - eigen
  run:
    - python 3

test:
  imports:
    - pychrono

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A physics engine for constrained multi-flexible-body dynamics

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
